// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dpmlhdbqzejijhnabges.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwbWxoZGJxemVqaWpobmFiZ2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4OTY3MDYsImV4cCI6MjA3NjQ3MjcwNn0.i-UNJiFHDIysIEOPbofhnlnxoJ0Sh8FbmWcQ_XyodIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);